### ISSUE TITLE
Broken ?

### ISSUE THREAD

**Issue by arshpreetsingh** [weihesdlegend/Autocomplete-System#15]
Is it broken, I am trying to do search but no Autocomplete is there, Small video tutorial or screen shots could be helpful.

**Comment by sananand007** [comment]
Please put a screen shot of the issue, Video tutorials is not possible, but we can provide a screen shot on issues
For me everything is good, just tested with the latest.

![image](https://user-images.githubusercontent.com/13934022/64068107-44e1a300-cbe8-11e9-9f57-4f2687614a20.png)

![image](https://user-images.githubusercontent.com/13934022/64068112-575bdc80-cbe8-11e9-8b1f-5a08dfbe5d1d.png)

**Comment by arshpreetsingh** [comment]
Oh , it work like this, I thought You also had implemented autocomplete on FrontEnd, something like folllowing: 
![Screen-Shot-2015-02-27-at-2 07 03-PM](https://user-images.githubusercontent.com/875061/64068178-f537c180-cc51-11e9-984c-4083ea2953b9.png)
BTW any plan for autocomplete For Frontend and is PR required for Docker implementation ?

**Comment by sananand007** [comment]
We can have this in a dockerfile, what do you want to put in the PR ? 
- if you want to use docker, please use Dockerfile, instead of compose

-  yes we have plans to add that to the FE, in time

**Comment by arshpreetsingh** [comment]
Yes, I was also thinking about only Dockerfile, And may be Examples/app instead of keeping your  flask app on root level, apart from that there is no "analytics.py" is this intentional ?

**Comment by sananand007** [comment]
- docker is not our main concern at the present, we might on production
- did not get what you mean by Examples, analytics.., reason for keeping less folders and files is to follow KISS
